-- 코드를 입력하세요
WITH CTE1 AS (
    SELECT BOOK_ID, SUM(SALES) AS NUM
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY BOOK_ID
), CTE2 AS (
    SELECT B.BOOK_ID, CATEGORY, AUTHOR_ID, NUM * PRICE AS TOTAL_SALES
    FROM BOOK B, CTE1 C
    WHERE B.BOOK_ID = C.BOOK_ID
)
SELECT C.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A, CTE2 C
WHERE A.AUTHOR_ID = C.AUTHOR_ID
GROUP BY (C.AUTHOR_ID, AUTHOR_NAME, CATEGORY)
ORDER BY AUTHOR_ID, CATEGORY DESC