-- 코드를 입력하세요
WITH CTE AS (
    SELECT COUNT(DISTINCT(NAME)) AS CNT, ID
    FROM CART_PRODUCTS
    WHERE NAME='Milk' OR NAME='Yogurt'
    GROUP BY CART_ID
    HAVING CNT = 2
)

SELECT DISTINCT(CART_ID)
FROM CART_PRODUCTS
WHERE ID IN (
    SELECT ID
    FROM CTE
)
GROUP BY ID