-- 코드를 입력하세요
WITH CTE AS (
    SELECT GROUP_CONCAT(NAME, ', ') AS NAME, CART_ID
    FROM CART_PRODUCTS
    GROUP BY CART_ID
)

SELECT CART_ID
FROM CTE
WHERE NAME LIKE '%Yogurt%' AND NAME LIKE '%Milk%'
ORDER BY CART_ID