WITH CTE AS (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk','Yogurt')
    GROUP BY (CART_ID, NAME)
), CTE2 AS (
    SELECT CART_ID, COUNT(CART_ID)
    FROM CTE
    GROUP BY CART_ID
    HAVING COUNT(CART_ID) = 2
)
SELECT CART_ID
FROM CTE2
ORDER BY CART_ID