-- 코드를 작성해주세요
WITH CTE AS (
    SELECT E1.ID, E1.PARENT_ID, E2.PARENT_ID AS ANCESTOR, E3.PARENT_ID AS ANCESTOR2
    FROM ECOLI_DATA E1
    JOIN ECOLI_DATA E2
    ON E1.PARENT_ID = E2.ID
    JOIN ECOLI_DATA E3
    ON E2.PARENT_ID = E3.ID
)
SELECT ID
FROM CTE
WHERE ANCESTOR IS NOT NULL AND ANCESTOR2 IS NULL
ORDER BY ID