-- 코드를 작성해주세요
WITH CTE AS(
    SELECT CASE 
        WHEN LENGTH IS NOT NULL THEN LENGTH
        ELSE 10
    END AS LENGTH
    FROM FISH_INFO
)

SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
FROM CTE

