WITH CTE AS (
    SELECT DISTINCT(C.CAR_ID), DAILY_FEE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01' AND TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-11-30'
    )
    AND CAR_TYPE IN ('SUV', '세단')
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT TRUNC(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) * 0.01, 0) AS FEE, C.CAR_TYPE, CAR_ID
    FROM CTE C
    JOIN (
        SELECT *
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE CAR_TYPE IN ('SUV', '세단') AND DURATION_TYPE = '30일 이상'
    )P
    ON C.CAR_TYPE = P.CAR_TYPE
)
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC