-- 코드를 입력하세요
WITH CTE AS (
    SELECT DISTINCT(CAR_ID) AS CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-11-30' AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01') 
), CTE2 AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE (CAR_ID NOT IN (SELECT CAR_ID FROM CTE)) AND (CAR_TYPE LIKE '세단' OR CAR_TYPE LIKE 'SUV')
), CTE3 AS (
    SELECT CAR_ID, C.CAR_TYPE, TRUNC(((100 - DISCOUNT_RATE) * 0.01 * daily_fee * 30), 0) AS FEE
    FROM CTE2 C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE (C.CAR_TYPE = P.CAR_TYPE) AND (DURATION_TYPE LIKE '30일 이상')
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM CTE3
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC