-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE((100 - REPLACE(P.DISCOUNT_RATE, '%', '')) * C.DAILY_FEE * 30 * 0.01, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT PLAN_ID, CAR_TYPE, DISCOUNT_RATE, DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE LIKE '30일 이상'
) P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= DATE('2022-11-01') AND START_DATE <= DATE('2022-11-30')
))
AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC