WITH CTE AS (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS GRADE
    FROM ECOLI_DATA
)
SELECT ID, CASE
    WHEN GRADE <= 0.25 THEN 'CRITICAL'
    WHEN GRADE <= 0.50 THEN 'HIGH'
    WHEN GRADE <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM CTE
ORDER BY ID