WITH CTE AS (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_PER
    FROM ECOLI_DATA
)
SELECT ID,
       CASE 
           WHEN SIZE_PER <= 0.25 THEN 'CRITICAL'
           WHEN SIZE_PER <= 0.50 THEN 'HIGH'
           WHEN SIZE_PER <= 0.75 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM CTE
ORDER BY ID;