SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE INSTR(SEX_UPON_INTAKE, 'Intact') = 1
) AND (INSTR(SEX_UPON_OUTCOME, 'Spayed') = 1 OR INSTR(SEX_UPON_OUTCOME, 'Neutered') = 1)
ORDER BY ANIMAL_ID