-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LOCATE('Intact', I.SEX_UPON_INTAKE) != 0
AND LOCATE('Intact', O.SEX_UPON_OUTCOME) = 0
ORDER BY ANIMAL_ID
