WITH CTE AS (
    SELECT S.USER_ID, S.SALES_DATE, I.GENDER
    FROM ONLINE_SALE S
    JOIN USER_INFO I
    ON I.USER_ID = S.USER_ID
    WHERE I.GENDER IS NOT NULL
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(USER_ID)) AS USERS
FROM CTE
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER