-- 코드를 입력하세요
WITH CTE AS (
    SELECT EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(S.USER_ID)) AS COUNT
    FROM ONLINE_SALE S, USER_INFO U
    WHERE S.USER_ID = U.USER_ID
    AND U.GENDER IS NOT NULL
    GROUP BY (EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), U.GENDER)
)

SELECT * FROM CTE
ORDER BY YEAR, MONTH, GENDER