-- 코드를 입력하세요
WITH CTE AS (
    SELECT CAR_ID, (END_DATE - START_DATE + 1) AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), CTE2 AS (
    SELECT CAR_ID, TO_CHAR(ROUND(AVG(DURATION), 1), 'FM9990.0') AS AVERAGE_DURATION
    FROM CTE
    GROUP BY CAR_ID
)
SELECT CAR_ID, AVERAGE_DURATION
FROM CTE2
WHERE AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC