WITH T1 AS (
    SELECT A.USER_ID, B.ONLINE_SALE_ID, B.PRODUCT_ID, B.SALES_AMOUNT, B.SALES_DATE
    FROM USER_INFO A
    JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
    WHERE TO_CHAR(A.JOINED, 'YYYY') = 2021
)
SELECT
    TO_CHAR(SALES_DATE, 'YYYY') YEAR
,   TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH
,   COUNT(DISTINCT USER_ID) PUCHASED_USERS
,   ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = 2021), 1) PUCHASED_RATIO
FROM T1
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')
ORDER BY 1 ASC, 2 ASC