-- 코드를 입력하세요
WITH CTE AS (
    SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT(S.USER_ID)) AS PUCHASED_USERS
    FROM ONLINE_SALE S
    JOIN USER_INFO I
    ON S.USER_ID = I.USER_ID
    WHERE (YEAR(I.JOINED) = '2021')
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
)

SELECT C.YEAR, C.MONTH, C.PUCHASED_USERS, ROUND((C.PUCHASED_USERS/T.CNT), 1) AS PUCHASED_RATIO
FROM CTE C
JOIN (
    SELECT COUNT(USER_ID) AS CNT
    FROM USER_INFO
    WHERE (YEAR(JOINED)) = '2021'
) T
ON 1=1
ORDER BY YEAR, MONTH