-- 코드를 입력하세요
WITH CTE AS (
    SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = '2021')
), CNT AS (
    SELECT COUNT(USER_ID) AS TOTAL
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = '2021'
), CTE2 AS (
    SELECT COUNT(DISTINCT(USER_ID)) AS CNT, YEAR, MONTH
    FROM CTE
    GROUP BY (YEAR, MONTH)
)
SELECT YEAR, MONTH, CNT AS PURCHASED_USERS, ROUND((CNT / TOTAL), 1) AS PURCHASED_RATIO
FROM CTE2 C2
JOIN CNT C
ON 1=1
ORDER BY TO_NUMBER(YEAR), TO_NUMBER(MONTH)