-- 코드를 입력하세요
WITH CTE AS (
    SELECT CAR_ID, CASE 
        WHEN ((TO_CHAR(START_DATE, 'YYYY-MM-DD') > '2022-10-16') OR (TO_CHAR(END_DATE, 'YYYY-MM-DD') < '2022-10-16')) THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT DISTINCT(CAR_ID), CASE 
    WHEN CAR_ID NOT IN (
    SELECT DISTINCT(CAR_ID)
    FROM CTE
    WHERE AVAILABILITY LIKE '대여중') THEN '대여 가능'
    ELSE '대여중'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC