-- 코드를 작성해주세요
-- 01, 02, 03/ 04, 05, 06/ 07, 08, 09/ 10, 11, 12
WITH CTE AS (
    SELECT CASE
        WHEN (DATE_FORMAT(DIFFERENTIATION_DATE, '%m') IN ('01', '02', '03')) THEN '1Q'
        WHEN (DATE_FORMAT(DIFFERENTIATION_DATE, '%m') IN ('04', '05', '06')) THEN '2Q'
        WHEN (DATE_FORMAT(DIFFERENTIATION_DATE, '%m') IN ('07', '08', '09')) THEN '3Q'
        ELSE '4Q'
    END AS QUARTER, ID
    FROM ECOLI_DATA
)


SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM CTE
GROUP BY QUARTER
ORDER BY QUARTER
