-- 코드를 입력하세요
WITH CTE AS (
    SELECT COUNT(HOST_ID), HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
)
SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM CTE
)
ORDER BY ID