-- 코드를 입력하세요
WITH CTE AS (
    SELECT HOST_ID, NAME, COUNT(HOST_ID) AS CNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING CNT >= 2 
)
SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM CTE
)
ORDER BY ID