-- 코드를 입력하세요
WITH CTE AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') LIKE '2022-05'
    GROUP BY PRODUCT_ID
)
SELECT P.PRODUCT_ID, PRODUCT_NAME, AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P, CTE C
WHERE P.PRODUCT_ID = C.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID
