SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY O.PRODUCT_ID, PRODUCT_NAME, PRICE
ORDER BY TOTAL_SALES DESC, PRODUCT_ID