WITH CTE AS (
    SELECT HISTORY_ID, H.CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE CAR_TYPE LIKE '트럭'
), CTE2 AS (
    SELECT CASE 
        WHEN DURATION >= 90 THEN '90일 이상'
        WHEN DURATION >= 30 THEN '30일 이상'
        WHEN DURATION >= 7 THEN '7일 이상'
    ELSE '7일 미만'
    END AS DURATION_TYPE, HISTORY_ID, CAR_ID, DURATION, DAILY_FEE
    FROM CTE
), CTE3 AS (
    SELECT C.DURATION_TYPE, HISTORY_ID, CAR_ID, DURATION, DAILY_FEE, IFNULL(DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM (
        SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE LIKE '트럭'
        ) P
    RIGHT OUTER JOIN CTE2 C
    ON P.DURATION_TYPE = C.DURATION_TYPE
), CTE4 AS (
    SELECT HISTORY_ID, ROUND(DAILY_FEE * DURATION * (100 - DISCOUNT_RATE) * 0.01, 0) AS FEE
    FROM CTE3
)

SELECT HISTORY_ID, SUM(FEE) AS FEE
FROM CTE4
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC
