WITH CTE AS (
    SELECT CASE 
            WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
            WHEN END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
            WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'  
    ELSE '7일 이하'
    END AS DURATION_TYPE, HISTORY_ID, DAILY_FEE * (END_DATE - START_DATE + 1) AS DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭'
)
SELECT HISTORY_ID, TRUNC(DAILY_FEE * (100 - NVL(DISCOUNT_RATE, 0)) * 0.01, 0) AS FEE
FROM CTE C
LEFT OUTER JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) P
ON C.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC