-- 코드를 입력하세요
WITH CTE AS (
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    UNION 
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM JULY
), CTE2 AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM CTE
    GROUP BY FLAVOR
)

SELECT * 
FROM (
    SELECT FLAVOR
    FROM CTE2
    ORDER BY TOTAL_ORDER DESC
) WHERE ROWNUM <= 3