SELECT FLAVOR
FROM (
    SELECT F.FLAVOR, SUM(F.TOTAL_ORDER)
    FROM FIRST_HALF F
    LEFT JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY SUM(F.TOTAL_ORDER) DESC
) A
LIMIT 3;

