WITH CTE AS (
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT C.HOUR, COUNT(ANIMAL_ID)
FROM CTE C
LEFT JOIN ANIMAL_OUTS O
ON TO_CHAR(O.DATETIME, 'HH24') = C.HOUR
GROUP BY HOUR
ORDER BY HOUR