-- 코드를 입력하세요
WITH CTE AS (
    SELECT LEVEL - 1 AS HOUR, 0 AS COUNT
    FROM    DUAL
    CONNECT BY LEVEL <= 24
)
SELECT A.HOUR, NVL(B.COUNT, 0) AS COUNT
FROM CTE A
LEFT OUTER JOIN (
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
) B
ON A.HOUR = B.HOUR
ORDER BY A.HOUR ASC