WITH CTE AS (
    SELECT ID, GROUP_CONCAT(CATEGORY, ', ') AS POSITION
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON S.CODE & D.SKILL_CODE = S.CODE
    GROUP BY ID
)
SELECT D.ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
JOIN CTE C
ON C.ID = D.ID
WHERE POSITION LIKE '%Front End%'
ORDER BY ID