-- 코드를 입력하세요
WITH CTE AS (
    SELECT WRITER_ID, SUM(PRICE) AS PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS LIKE 'DONE'
    GROUP BY WRITER_ID
)

SELECT U.USER_ID, U.NICKNAME, C.PRICE AS TOTAL_SALES 
FROM CTE C, USED_GOODS_USER U
WHERE C.WRITER_ID = U.USER_ID
AND C.PRICE >= 700000
ORDER BY TOTAL_SALES