-- 코드를 작성해주세요
WITH CTE AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
), CTE2 AS (
    SELECT CASE 
        WHEN AVG_SCORE >= 96 THEN 'S'
        WHEN AVG_SCORE >= 90 AND AVG_SCORE < 96 THEN 'A'
        WHEN AVG_SCORE >= 80 AND AVG_SCORE < 90 THEN 'B'
        ELSE 'C'
    END AS GRADE, EMP_NO
    FROM CTE
)

SELECT H.EMP_NO, EMP_NAME, GRADE, CASE
    WHEN GRADE = 'S' THEN (0.2 * SAL)
    WHEN GRADE = 'A' THEN (0.15 * SAL)
    WHEN GRADE = 'B' THEN (0.1 * SAL)
    ELSE SAL * 0
END AS BONUS
FROM HR_EMPLOYEES H
JOIN CTE2 C
ON H.EMP_NO = C.EMP_NO
ORDER BY EMP_NO