WITH CTE AS (
    SELECT CASE 
            WHEN GRADE >= 96 THEN 'S'
            WHEN GRADE >= 90 THEN 'A'
            WHEN GRADE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE, EMP_NO
    FROM (
        SELECT EMP_NO, ROUND(AVG(SCORE), 1) AS GRADE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) A
)
SELECT E.EMP_NO, EMP_NAME, GRADE, CASE
    WHEN GRADE = 'S' THEN SAL * 0.2
    WHEN GRADE = 'A' THEN SAL * 0.15
    WHEN GRADE = 'B' THEN SAL * 0.1
ELSE 0
END AS BONUS
FROM HR_EMPLOYEES E
JOIN CTE C
ON E.EMP_NO = C.EMP_NO
ORDER BY EMP_NO