WITH CTE AS (
    SELECT MEMBER_ID
    FROM (
        SELECT COUNT(REVIEW_ID), MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
    ) A
    WHERE ROWNUM <= 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT * FROM CTE)
ORDER BY REVIEW_DATE, REVIEW_TEXT