-- 코드를 입력하세요
WITH CTE AS (
    SELECT * FROM (
        SELECT MEMBER_ID, COUNT(REVIEW_ID)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(REVIEW_ID) DESC
    ) WHERE ROWNUM <= 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE 
FROM MEMBER_PROFILE M, REST_REVIEW R
WHERE M.MEMBER_ID = R.MEMBER_ID
AND R.MEMBER_ID IN (
    SELECT MEMBER_ID FROM CTE
)
ORDER BY REVIEW_DATE, REVIEW_TEXT