-- 코드를 작성해주세요
SELECT DISTINCT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
WHERE I.ITEM_ID IN (SELECT DISTINCT T.ITEM_ID
    FROM ITEM_TREE T
    JOIN ITEM_INFO I
    ON T.ITEM_ID = I.ITEM_ID
    WHERE T.PARENT_ITEM_ID IN (SELECT DISTINCT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY LIKE 'RARE'))
ORDER BY ITEM_ID DESC
