WITH CTE AS (
    SELECT CAR_ID, COUNT(HISTORY_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM CTE) AND TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC