-- 코드를 입력하세요
WITH CTE AS (
    SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
    GROUP BY (EXTRACT(MONTH FROM START_DATE), CAR_ID)
), CTE2 AS (
    SELECT CAR_ID, SUM(RECORDS) AS TOTAL_COUNT
    FROM CTE
    GROUP BY CAR_ID
    HAVING SUM(RECORDS) >= 5
)
SELECT MONTH, CAR_ID, RECORDS
FROM CTE
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CTE2
) 
AND RECORDS != 0
ORDER BY MONTH, CAR_ID DESC