# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
#     GROUP BY CAR_ID
#     HAVING 
# )
# GROUP BY CAR_ID, MONTH(START_DATE)
# ORDER BY MONTH(START_DATE), CAR_ID DESC

# WITH CTE AS (
#     SELECT CAR_ID, COUNT(CAR_ID) AS COUNT
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
#     GROUP BY CAR_ID
#     HAVING COUNT >= 5
# ) 
# SELECT MONTH(C1.START_DATE) AS MONTH, C2.CAR_ID, COUNT(C1.CAR_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
# JOIN CTE C2
# ON C1.CAR_ID = C2.CAR_ID
# GROUP BY C1.CAR_ID, MONTH(C1.START_DATE)
# HAVING RECORDS > 0
# ORDER BY MONTH ASC, CAR_ID DESC

WITH CTE AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING CNT >= 5
) 
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CTE
)
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING RECORDS != 0
ORDER BY MONTH ASC, CAR_ID DESC