-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
WHERE E.POSITION NOT LIKE '팀장'
GROUP BY G.EMP_NO
ORDER BY SUM(G.SCORE) DESC
LIMIT 1