-- 코드를 입력하세요
WITH CTE AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (
        SELECT MAX(VIEWS)
        FROM USED_GOODS_BOARD
    )
)

SELECT CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('/home/grep/src/', BOARD_ID), '/'), FILE_ID), FILE_NAME), FILE_EXT) AS FILE_PATH 
FROM USED_GOODS_FILE
WHERE BOARD_ID IN (
    SELECT BOARD_ID
    FROM CTE
)
ORDER BY FILE_ID DESC