-- 코드를 입력하세요
WITH CTE AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') LIKE '2022-01'
    GROUP BY BOOK_ID
)

SELECT B.CATEGORY, SUM(C.SALES) AS TOTAL_SALES
FROM BOOK B, CTE C
WHERE B.BOOK_ID = C.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY CATEGORY