-- 코드를 입력하세요
WITH CTE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE ((CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX_PRICE
    FROM CTE
)) AND (CATEGORY IN ('과자', '국', '김치', '식용유'))
ORDER BY MAX_PRICE DESC