WITH CTE AS (
    SELECT FISH_TYPE, COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH, 10)) >= 33
)

SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM CTE
ORDER BY FISH_TYPE