-- 코드를 작성해주세요
WITH CTE AS
(
    SELECT AVG(LENGTH) AS LENGTH, FISH_TYPE
        FROM (
            SELECT CASE WHEN LENGTH IS NULL THEN 10
                    ELSE LENGTH
                END AS LENGTH, ID, FISH_TYPE
            FROM FISH_INFO) F
        GROUP BY FISH_TYPE
        HAVING LENGTH >= 33
)
SELECT COUNT(F.ID) AS FISH_COUNT, MAX(F.LENGTH) AS MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO F
JOIN CTE C
ON F.FISH_TYPE = C.FISH_TYPE
GROUP BY F.FISH_TYPE
ORDER BY FISH_TYPE

