-- 코드를 작성해주세요
WITH CTE AS (
    SELECT ID, EMAIL, SKILL_CODE, NAME, CATEGORY 
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON 1 = 1
    WHERE SKILL_CODE & CODE = CODE
), CTE2 AS (
    SELECT ID, GROUP_CONCAT(CATEGORY) AS CATEGORY, GROUP_CONCAT(NAME SEPARATOR ', ') AS SKILL
    FROM CTE
    GROUP BY ID
), CTE3 AS (
    SELECT CASE
        WHEN CATEGORY LIKE '%Front End%' AND SKILL LIKE '%Python%' THEN 'A'
        WHEN SKILL LIKE '%C#%' THEN 'B'
        WHEN CATEGORY LIKE '%Front End%' THEN 'C'
    END AS GRADE, D.ID, EMAIL
    FROM DEVELOPERS D 
    JOIN CTE2 C
    ON D.ID = C.ID
    ORDER BY GRADE, ID
)

SELECT * FROM CTE3 WHERE GRADE IS NOT NULL;