-- 코드를 작성해주세요
WITH CTE AS (
    SELECT ID, EMAIL, NAME, S.CODE, CATEGORY
    FROM SKILLCODES S
    JOIN DEVELOPERS D
    ON S.CODE & D.SKILL_CODE = S.CODE
), CTE2 AS (
    SELECT ID, GROUP_CONCAT(NAME, ', ') AS SKILLS, GROUP_CONCAT(CATEGORY, ', ') AS CATEGORY
    FROM CTE
    GROUP BY ID
), CTE3 AS (
    SELECT CASE
        WHEN (SKILLS LIKE '%Python%' AND CATEGORY LIKE '%Front End%') THEN 'A'
        WHEN SKILLS LIKE '%C#%' THEN 'B'
        WHEN CATEGORY LIKE '%Front End%' THEN 'C'
        ELSE 'D'
    END AS GRADE, ID
    FROM CTE2
)
SELECT GRADE, D.ID, EMAIL
FROM CTE3 C
JOIN DEVELOPERS D
ON C.ID = D.ID
WHERE GRADE != 'D'
ORDER BY GRADE, ID