-- 코드를 입력하세요
SELECT IFNULL(PRICE_GROUP, 0) AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
FROM (
    SELECT CASE
        WHEN PRICE THEN TRUNCATE(PRICE, -4)
    END AS PRICE_GROUP, PRODUCT_ID
    FROM PRODUCT
) A
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP